version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      rm -f tmp/pids/server.pid;
      bundle exec rails db:prepare;
      mkdir -p /etc/ssl/private;
      chmod 700 /etc/ssl/private;
      ./bin/rails server -b 'ssl://0.0.0.0:443?key=/etc/ssl/private/moriappli-emotion.com-key.pem&cert=/etc/ssl/certs/moriappli-emotion.com.pem'"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/rails/node_modules
      - ./docker/certs/moriappli-emotion.com.pem:/etc/ssl/certs/moriappli-emotion.com.pem:ro
      - ./docker/certs/moriappli-emotion.com-key.pem:/etc/ssl/private/moriappli-emotion.com-key.pem:ro

    environment:
      - TZ=Asia/Tokyo
      - SESSION_SECRET=${SESSION_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - REDIS_URL=redis://redis:6379/0
      - SOUNDCLOUD_REDIRECT_URI=https://moriappli-emotion.com/auth/soundcloud/callback
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - RAILS_ENV=production
    env_file:
      - .env.production
    ports:
      - "443:443"
    depends_on:
      redis:
        condition: service_started
    restart: always

volumes:
  bundle_data:
  node_modules:
