services:
  web:
    env_file:
      - .env.production

    environment:
      # override したいものだけ
      - RAILS_ENV=production
      - SOUNDCLOUD_REDIRECT_URI=https://moriappli-emotion.com/auth/soundcloud/callback

    volumes:
      # ホストのソースをマウントして即反映
      - .:/rails
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/rails/node_modules

    # Dockerfile の ENTRYPOINT を無効化
    entrypoint: []

    # (1) db:prepare → (2) Rails(production＋自動リロードON) → (3) esbuild watch
    command:
      - bash
      - -c
      - |
        cd /rails &&
        bundle exec rails db:prepare &&
        bundle exec rails server \
          -b 'ssl://0.0.0.0:443?key=/etc/ssl/private/moriappli-emotion.com-key.pem&cert=/etc/ssl/certs/moriappli-emotion.com.pem' \
          -e production & \
        yarn build --watch
