default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db  # ← 必ずここでhostを指定

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    variables:
      sslmode: require
