default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db  # ← 必ずここでhostを指定

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  primary: &primary_production
    <<: *default
    database: app_production
    username: postgres
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
    host: db # ← ここも追加

  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate
    host: db # ← ここも追加

  queue:
    <<: *primary_production
    database: app_production_queue
    migrations_paths: db/queue_migrate
    host: db # ← ここも追加

  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
    host: db # ← ここも追加
